/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InstantDateTimeInfo;
import dao.BookingDAO;
import dao.TableListDAO;
import dao.TableTypeDAO;
import model.TableList;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
//import controller.MultiLineTableCellRenderer;
/**
 *
 * @author Admin
 */
public class TableListView extends javax.swing.JFrame {

    /**
     * Creates new form TableList
     */
    public TableListView() {
        try {
//            chuyển giao diện sang giống ios
            UIManager.setLookAndFeel(new FlatLightLaf());
            initComponents();
            setLocationRelativeTo(null);

            // Khởi tạo mô hình dữ liệu cho bảng
            tableModel = (DefaultTableModel) tableTable.getModel();

            // Gọi phương thức để thêm dữ liệu vào bảng
            addDataToTable();
            // Tạo đối tượng MultiLineTableCellRenderer
//            MultiLineTableCellRenderer multiLineRenderer = new MultiLineTableCellRenderer();

            // Áp dụng renderer cho cột có nội dung đa dòng (ở đây giả sử cột index 3, 4 và 5 có nội dung đa dòng)
//            int[] multiLineColumns = {3, 4, 5};
//            for (int columnIndex : multiLineColumns) {
//                tableTable.getColumnModel().getColumn(columnIndex).setCellRenderer(multiLineRenderer);
//            }
            // Thiết lập chiều cao của các hàng trong bảng
//            tableTable.setRowHeight(60); // Đặt giá trị lớn hơn tùy thuộc vào nhu cầu của bạn

        }catch (Exception e){
            e.printStackTrace();
        }
        customizeTableAppearance();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputDateFillter = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputCapacityFilter = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        selecType = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        btnSelectTable = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Type", "Capacity", "Rental start time", "Rental end time", "Date", "Status"
                }
        ) {
            Class[] types = new Class [] {
                    Integer.class, String.class, Integer.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
           tableTableMouseClicked(evt);

            }
        });
        jScrollPane1.setViewportView(tableTable);
        if (tableTable.getColumnModel().getColumnCount() > 0) {
            tableTable.getColumnModel().getColumn(0).setPreferredWidth(6);
            tableTable.getColumnModel().getColumn(1).setPreferredWidth(12);
            tableTable.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableTable.getColumnModel().getColumn(5).setPreferredWidth(10);
            tableTable.getColumnModel().getColumn(6).setPreferredWidth(10);

        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setText("Filter by date :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputDateFillter, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(inputDateFillter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel3.setText("Filter by capacity :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputCapacityFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(inputCapacityFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel4.setText("Filter by type :");


//        thêm dữ liệu vào select list
        String[] selectList = TableTypeDAO.getInstance().getAll().stream()
                .map(s -> s.getName())
                .toArray(String[]::new);
        selecType.setModel(new javax.swing.DefaultComboBoxModel<>(selectList));






        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecType, 0, 272, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(selecType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        btnFilter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFilter.setText("Filter");
        btnFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilterMouseClicked(evt);
            }
        });
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        btnSelectTable.setBackground(new java.awt.Color(54, 235, 191));
        btnSelectTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectTable.setText("Select table");
        btnSelectTable.setBorder(null);
        btnSelectTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectTableMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TABLE LIST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        searchTableList();
        System.out.println("tìm kiếm");

    }

    private void btnSelectTableMouseClicked(java.awt.event.MouseEvent evt) {
//        this.filterTypeInput = selecType.getSelectedItem().toString();
//        System.out.println("select value: " + this.filterTypeInput);
    }

    private void btnFilterMouseClicked(java.awt.event.MouseEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnSelectTable;
    private javax.swing.JTextField inputCapacityFilter;
    private javax.swing.JTextField inputDateFillter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selecType;
//    đối tượng bảng
    private javax.swing.JTable tableTable;
    private DefaultTableModel tableModel;
//    dữ liệu truyền vào bảng
    private Object[][] data;
//    dữ liệu lọc bảng
    private String filterTypeInput ;
    private String CapacityInput;
    private String dateInput;
    private Object lockObject = new Object();


//    căn giữa chữ cho bảng
    private void customizeTableAppearance() {
        // Tạo một đối tượng DefaultTableCellRenderer để tùy chỉnh cách hiển thị của các ô trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa chữ trong tất cả các cột của bảng
        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            tableTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Điều chỉnh kích thước cột tuỳ theo nội dung trong ô
        tableTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
//    hàm lấy dữ liệu dc chọn từ bảng
    private void tableTableMouseClicked(java.awt.event.MouseEvent evt){
        int rowNumber = tableTable.getSelectedRow();
        TableModel tblModel = tableTable.getModel();

        Integer id = Integer.valueOf(tblModel.getValueAt(rowNumber, 0 ).toString());
        System.out.println(id);
    }

//    hàm thêm dữ liệu vào bảng
    private void addDataToTable() {
        List<model.Booking> bookingList = BookingDAO.getInstance().getAll();
        // Sử dụng HashSet để lưu trữ các phần tử không trùng lặp
        Set<Integer> uniqueElements = new HashSet<>();
        Object[][] dataOnBooking = bookingList.stream().map(
                s -> new Object[]{
                        s.getTable().getId(),  // id bàn
                        s.getTable().getType().getName(),  // loại bàn
                        s.getTable().getSeatingCapacity(),   // số ghế
                        InstantDateTimeInfo.getTime(s.getInfo().getStart(),1),  // giờ bắt đầu
                        InstantDateTimeInfo.getTime(s.getInfo().getEnd(),1),    // giờ kết thúc
                        InstantDateTimeInfo.getTime(s.getInfo().getStart(),2),  // ngày
                        s.getTable().getFlag(),  // trạng thái của bàn
                        uniqueElements.add(s.getTable().getId())
                }

        ).toArray(Object[][]::new);

        List<model.TableList> tableLists = TableListDAO.getInstance().getAll();

        Object[][] dataNoneBooking = tableLists.stream()
                .map(s -> {
                    int tableId = s.getId().intValue();
                    if (!uniqueElements.contains(tableId)) { // Đảo ngược điều kiện từ contains thành không contains
                        return new Object[]{
                                s.getId(),    // id bàn
                                s.getType().getName(),  // loại bàn
                                s.getSeatingCapacity(),  // số ghế
                                "",
                                "",
                                "",
                                s.getFlag()
                        };
                    } else {
                        return null;
                    }
                })
                .filter(Objects::nonNull)
                .toArray(Object[][]::new);
        Object[][] allBooking = concatenateArrays(dataNoneBooking,dataOnBooking);
//        sắp xếp theo id
        Arrays.sort(allBooking, Comparator.comparingInt(arr -> (int) arr[0]));

        this.data = allBooking;
        Arrays.stream(data).map(s->new Object[]{

        }).toArray(Object[][]::new);

        // Thêm từng hàng dữ liệu vào bảng
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
        // Cập nhật bảng để hiển thị dữ liệu mới
        tableModel.fireTableDataChanged();
    }

    public synchronized  void searchTableList() {

        String a = "vip1";
        final String b = "4";
        String c = "2023-08-25";

        synchronized (lockObject) {
            // Tạo luồng dữ liệu từ mảng
            Stream<Object[]> dataStream1 = Arrays.stream(data);
            if (!a.equals("")) {
                data = dataStream1.filter(row -> row[1].equals(a)).toArray(Object[][]::new);;

            }

            Stream<Object[]> dataStream2 = Arrays.stream(data);
            // In ra giá trị của dataStream2
            if (true) {
                //            ép về kiểu string trước khi so sánh
                data = dataStream2.filter(row -> (row[2].toString()).equals(b)).toArray(Object[][]::new);;
            }

            Stream<Object[]> dataStream3 = Arrays.stream(data);
            if (!c.equals("")) {
                data = dataStream3.filter(row -> row[5].toString().contains(c)).toArray(Object[][]::new);;
            }
        }








//        Object[][] arrays1 = concatenateArrays(filteredData1,filteredData2);


        // Xóa dữ liệu hiện có trong bảng
        tableModel.setRowCount(0);




        //        sắp xếp theo id trước khi thêm vào bảng
//        Arrays.sort(this.data, Comparator.comparingInt(arr -> (int) arr[0]));


        // Thêm từng hàng dữ liệu vào bảng
        for (Object[] row : this.data) {
            tableModel.addRow(row);
        }

        // Cập nhật bảng để hiển thị dữ liệu mới
        tableModel.fireTableDataChanged();
    }

    // hàm nối mảng
    public static Object[][] concatenateArrays(Object[][] arr1, Object[][] arr2) {
        int arr1Length = arr1.length;
        int arr2Length = arr2.length;
        Object[][] result = new Object[arr1Length + arr2Length][];

        System.arraycopy(arr1, 0, result, 0, arr1Length);
        System.arraycopy(arr2, 0, result, arr1Length, arr2Length);

        return result;
    }
    // End of variables declaration
}
